<?php
/* ==========================================================================
   Password gate for the applications inbox.

   Required at the top of every page in this directory. Nothing below the
   require() runs until a valid session exists.

   WHERE THE PASSWORD LIVES
   ------------------------
   Not in this file, and not anywhere under public_html. On first visit the
   page offers to set one; the resulting hash is written to
   ../takwa-admin-config.php, a sibling of the web root. Only a hash is ever
   stored -- password_hash() with the default algorithm -- so the file is
   useless to anyone who reads it, and there is no URL that reaches it anyway.

   WHY NOT A PASSWORD IN JAVASCRIPT
   --------------------------------
   Because the browser has to receive the page before it can check anything,
   so View Source would show both the password and the applications. The check
   has to happen here, on the server, before a single byte of the inbox is
   sent.

   THROTTLING
   ----------
   Five wrong guesses locks the form for fifteen minutes, counted in a file
   beside the config. Without it, a long-lived admin password on a public URL
   is a few hours of scripted guessing away from being someone's date of birth
   and salary history.

   Apache Basic auth (cPanel > Directory Privacy) still works on top of this
   if it is switched on -- an authenticated REMOTE_USER is accepted as well.
   Two locks are better than one, and neither depends on the other.
   ========================================================================== */

declare(strict_types=1);

const AUTH_CONFIG   = '/takwa-admin-config.php';
const AUTH_ATTEMPTS = '/takwa-admin-attempts.json';
const MAX_TRIES     = 5;
const LOCK_SECONDS  = 900;

function auth_base(): string
{
    return dirname($_SERVER['DOCUMENT_ROOT']);
}

function auth_hash(): ?string
{
    $path = auth_base() . AUTH_CONFIG;
    if (!is_file($path)) {
        return null;
    }
    $data = require $path;
    return is_array($data) && !empty($data['hash']) ? (string) $data['hash'] : null;
}

function auth_save_hash(string $hash): bool
{
    $path = auth_base() . AUTH_CONFIG;
    $body = "<?php\n/* Admin password hash. Generated by admin/auth.php.\n"
          . "   Delete this file to reset the password. */\n"
          . "return " . var_export(['hash' => $hash], true) . ";\n";
    if (file_put_contents($path, $body, LOCK_EX) === false) {
        return false;
    }
    @chmod($path, 0600);
    return true;
}

/* ------------------------------------------------------------- throttle -- */
function auth_attempts(): array
{
    $path = auth_base() . AUTH_ATTEMPTS;
    if (!is_file($path)) {
        return ['count' => 0, 'until' => 0];
    }
    $d = json_decode((string) file_get_contents($path), true);
    return is_array($d) ? $d + ['count' => 0, 'until' => 0] : ['count' => 0, 'until' => 0];
}

function auth_record_failure(): void
{
    $a = auth_attempts();
    $a['count'] = (int) $a['count'] + 1;
    if ($a['count'] >= MAX_TRIES) {
        $a['until'] = time() + LOCK_SECONDS;
        $a['count'] = 0;
    }
    @file_put_contents(auth_base() . AUTH_ATTEMPTS, json_encode($a), LOCK_EX);
    @chmod(auth_base() . AUTH_ATTEMPTS, 0600);
}

function auth_clear_failures(): void
{
    @unlink(auth_base() . AUTH_ATTEMPTS);
}

function auth_locked_for(): int
{
    $a = auth_attempts();
    return max(0, (int) $a['until'] - time());
}

/* --------------------------------------------------------------- session -- */
session_set_cookie_params([
    'httponly' => true,
    'samesite' => 'Strict',
    'secure'   => !empty($_SERVER['HTTPS']),
]);
session_start();

/* Apache Basic auth, if it is configured, counts as signed in */
$apacheUser = $_SERVER['REMOTE_USER']
    ?? $_SERVER['PHP_AUTH_USER']
    ?? $_SERVER['REDIRECT_REMOTE_USER']
    ?? '';

if ($apacheUser !== '') {
    $_SESSION['admin'] = $apacheUser;
}

if (isset($_GET['logout'])) {
    $_SESSION = [];
    session_destroy();
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}

$stored  = auth_hash();
$error   = '';
$notice  = '';

/* ------------------------------------------------------------ first run -- */
if ($stored === null && ($_POST['new_password'] ?? '') !== '') {
    $new     = (string) $_POST['new_password'];
    $confirm = (string) ($_POST['confirm_password'] ?? '');
    if (strlen($new) < 10) {
        $error = 'Use at least 10 characters.';
    } elseif ($new !== $confirm) {
        $error = 'The two passwords do not match.';
    } elseif (!auth_save_hash(password_hash($new, PASSWORD_DEFAULT))) {
        $error = 'Could not write the password file. Check permissions on '
               . auth_base() . '.';
    } else {
        session_regenerate_id(true);
        $_SESSION['admin'] = 'admin';
        header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
        exit;
    }
}

/* --------------------------------------------------------------- log in -- */
if ($stored !== null && ($_POST['password'] ?? '') !== '') {
    if (auth_locked_for() > 0) {
        $error = 'Too many attempts. Try again in '
               . ceil(auth_locked_for() / 60) . ' minutes.';
    } elseif (password_verify((string) $_POST['password'], $stored)) {
        auth_clear_failures();
        session_regenerate_id(true);
        $_SESSION['admin'] = 'admin';
        header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
        exit;
    } else {
        auth_record_failure();
        $error = 'Wrong password.';
    }
}

if (!empty($_SESSION['admin'])) {
    return;                       /* signed in: the calling page continues */
}

/* ------------------------------------------------------------ the screen -- */
$setup = ($stored === null);
$locked = auth_locked_for();
http_response_code(401);
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title><?= $setup ? 'Set a password' : 'Sign in' ?> &mdash; Takwa</title>
<style>
:root{ color-scheme: light dark;
  --bg:#f6f7f6; --card:#fff; --line:#dfe1de; --ink:#12211f; --dim:#6b7a76;
  --accent:#2C6728; --bad:#A33A3A; }
@media (prefers-color-scheme: dark){ :root{
  --bg:#0f1614; --card:#17211f; --line:#2a3835; --ink:#e8efec; --dim:#93a5a0;
  --accent:#73ED7C; --bad:#f0a0a0; } }
*{box-sizing:border-box}
body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;
  background:var(--bg);color:var(--ink);
  font:15px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
.box{background:var(--card);border:1px solid var(--line);border-radius:16px;
  padding:34px 30px;width:100%;max-width:400px}
h1{margin:0 0 6px;font-size:20px}
p.sub{margin:0 0 22px;color:var(--dim);font-size:14px}
label{display:block;font-size:13.5px;font-weight:600;margin:0 0 6px}
input{width:100%;padding:11px 13px;margin-bottom:16px;border:1px solid var(--line);
  border-radius:8px;background:var(--bg);color:var(--ink);font:inherit}
input:focus{outline:2px solid var(--accent);outline-offset:1px;border-color:transparent}
button{width:100%;padding:11px;border:0;border-radius:8px;background:var(--accent);
  color:#fff;font:inherit;font-weight:600;cursor:pointer}
@media (prefers-color-scheme: dark){ button{color:#0f1614} }
.err{color:var(--bad);font-size:14px;margin:0 0 16px;font-weight:600}
.hint{color:var(--dim);font-size:13px;margin:18px 0 0;line-height:1.6}
</style>
</head>
<body>
<form class="box" method="post" autocomplete="off">
<?php if ($setup): ?>
    <h1>Set a password</h1>
    <p class="sub">No password has been set for the applications inbox yet.
       Choose one now &mdash; this screen is only offered once.</p>
    <?php if ($error): ?><p class="err"><?= htmlspecialchars($error, ENT_QUOTES) ?></p><?php endif; ?>
    <label for="new_password">New password</label>
    <input type="password" id="new_password" name="new_password" required minlength="10" autofocus>
    <label for="confirm_password">Confirm</label>
    <input type="password" id="confirm_password" name="confirm_password" required minlength="10">
    <button type="submit">Set password</button>
    <p class="hint">At least 10 characters. Only a hash is stored, outside the
       web root. To reset it later, delete
       <code>takwa-admin-config.php</code> from the folder above public_html.</p>
<?php else: ?>
    <h1>Applications</h1>
    <p class="sub">Sign in to read the inbox.</p>
    <?php if ($error): ?><p class="err"><?= htmlspecialchars($error, ENT_QUOTES) ?></p><?php endif; ?>
    <?php if ($locked > 0 && !$error): ?>
        <p class="err">Locked for <?= (int) ceil($locked / 60) ?> more minutes.</p>
    <?php endif; ?>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" required autofocus
           <?= $locked > 0 ? 'disabled' : '' ?>>
    <button type="submit" <?= $locked > 0 ? 'disabled' : '' ?>>Sign in</button>
<?php endif; ?>
</form>
</body>
</html>
<?php
exit;
